[package]
name = "pipe_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.20"
reqwest = {version="0.11.12", features=["blocking"]}
anyhow = "1.0.51"
lz4 = "1.24.0"
