[workspace]
members = [
    "pipe_downloader_lib",
]

[workspace.package]
authors = ["Sieciech Czajka <sieciech.czajka@golem.network>"]
version = "0.4.1"
edition = "2021"
license = "MIT"

[[bin]]
name = "pipe_downloader"

[package]
name = "pipe_downloader"
description = "Fast downloader + extractor for *.tar.gz, *tar.lz4 and *.tar.bz2 files."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[workspace.dependencies]
anyhow = "1.0.51"
serde_json = "1.0.89"
structopt = "0.3.26"
env_logger = "0.10.0"
reqwest = "0.11.12"
lz4 = "^1.24.0"
log = "0.4.17"
flate2 = "1.0.24"
tar = "0.4.38"
humansize = "2.1.2"
bzip2 = "0.4.3"
serde = "1.0"
lz4_flex = "^0.9.5"
chrono = "0.4.23"

[dependencies]
pipe_downloader_lib = { path = "pipe_downloader_lib" }
anyhow = { workspace = true }
serde_json = { workspace = true }
structopt = { workspace = true }
env_logger = { workspace = true }

[profile.release]
lto = true
strip = true