[package]
name = "pipe_downloader"
version = "0.4.1"
edition = "2021"
description = "Fast downloader + extractor for *.tar.gz, *tar.lz4 and *.tar.bz2 files."
license = "MIT"

[workspace]

[dependencies]
pipe_downloader_lib = { path = "pipe_downloader_lib", features = [""] }
serde_json = "1.0.89"
structopt = "0.3.26"
env_logger = "0.10.0"
anyhow = "1.0.51"

[profile.release]
lto = true
strip = true