[package]
name = "pipe_downloader"
version = "0.4.1"
edition = "2021"
description = "Fast downloader + extractor for *.tar.gz, *tar.lz4 and *.tar.bz2 files."
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version="0.11.12", default-features=false, features=["blocking", "rustls-tls"]}
anyhow = "1.0.51"
lz4 = "^1.24.0"
libc = "^0.2.108"
log = "0.4.17"
flate2 = "1.0.24"
tar = "0.4.38"
human_bytes = "0.4.1"
bzip2 = "0.4.3"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
chrono = { version="^0.4.22", features=["serde"] }
lz4_flex = "^0.9.5"

[dev-dependencies]
env_logger = "^0.10.0"
structopt = "^0.3.25"

