name: CI build

on:
  push:
    branches:
      - main
      - release/*
      - scx1332/*

jobs:
  build:
    runs-on: ${{ matrix.build-on }}
    strategy:
      matrix:
        include:
          - cpu: x86_64
            os: win
            target: x86_64-pc-windows-msvc
            build-on: windows-latest
            use-cross: false
            install-musl: false
            install-openssl: false
            exe: ".exe"
            run-tests: true
          - cpu: x86_64
            os: linux
            target: x86_64-unknown-linux-musl
            build-on: ubuntu-latest
            use-cross: false
            install-musl: true
            install-openssl: true
            exe: ""
            run-tests: true
          - cpu: aarch64
            os: linux
            target: aarch64-unknown-linux-musl
            build-on: ubuntu-latest
            use-cross: true
            install-openssl: true
            install-musl: false
            exe: ""
            run-tests: false
          - cpu: aarch64
            os: macOS
            target: aarch64-apple-darwin
            build-on: macos-latest
            use-cross: true
            install-openssl: false
            install-musl: false
            exe: ""
            run-tests: false
          - cpu: x86_64
            os: macOS
            target: x86_64-apple-darwin
            build-on: macos-latest
            use-cross: false
            install-openssl: false
            install-musl: false
            exe: ""
            run-tests: true

    name: Build Release ${{ matrix.cpu }} ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install musl-tools if needed
        if: ${{ matrix.install-musl }}
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install openssl if needed
        if: ${{ matrix.install-openssl }}
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Install Rust stable toolchain ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Run tests
        if: ${{ matrix.run-tests }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target ${{ matrix.target }} -- --nocapture

      - name: Build binary target/${{ matrix.target }}/release/pipe_downloader
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: --release --bin pipe_downloader --target ${{ matrix.target }}

